version: "3.3"
services:
  telegram_notifier:
    image: apollon76/telegram_notifier:latest
    build: .
    environment:
      - RUST_BACKTRACE=full
      - CHAT_ID=${CHAT_ID:-unset}
      - BOT_TOKEN=${BOT_TOKEN:-unset}
      - ROCKET_ENV=${ROCKET_ENV:-unset}
      - ROCKET_PORT=${ROCKET_PORT:-8000}
      - ROCKET_ADDRESS=${ROCKET_ADDRESS:-0.0.0.0}
    restart: always
    ports:
    - 8000:8000
    expose:
    - "8000"
