name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag apollon76/telegram_notifier:latest
      
    - name: Login
      env:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: docker login -u apollon76 -p "$DOCKER_HUB_PASSWORD"
      
    - name: Push
      run: docker push apollon76/telegram_notifier:latest
